--- #YAML:1.0
name:               Sphinx-Manager
version:            0.06
abstract:           Sphinx search engine management (start/stop)
author:
    - Jon Schutz <jon@jschutz.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Class::Accessor::Fast:  0
    File::Spec:           0
    FindBin:              0
    Path::Class:          0
    Proc::ProcessTable:   0
    Sphinx::Config:       0.09
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
